repos:
  - repo: https://github.com/beholdenkey/nexus-sdk
    rev: '0.1.0'
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]