name: Nexus SDK Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    runs-on: ubuntu-latest
    container:
      image: python:${{ matrix.python-version }}-alpine

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Test with pytest
        run: |
          pytest --cov=nexus_sdk
